Update newmacaddr script

diff --git a/newmacaddr b/newmacaddr
--- a/newmacaddr
+++ b/newmacaddr
@@ -3,7 +3,19 @@
 # Generates a random mac address and configures en0
 ###################################################
 
+# Evals a function and exits the script if any error occured
+function run() {
+  cmd_output=$(eval $1)
+  return_value=$?
+  if [ $return_value != 0 ]; then
+    echo "Command $1 failed"
+    exit -1
+  fi
+  return $return_value
+}
+
 MAC=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
-sudo airport -z
-sudo ifconfig en0 ether $MAC
-networksetup -detectnewhardware
+
+run "sudo airport -z"
+run "sudo ifconfig en0 ether $MAC"
+run "networksetup -detectnewhardware"
